spring.application.name=shortly

spring.datasource.url=jdbc:mysql://localhost:3306/shortly
spring.datasource.username=root
spring.datasource.password=Surya@949024

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
jwt.expiration=86400000
server.port=8080